/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItem } from "./components/menu/types";
import { PartialOptions } from "overlayscrollbars";
export { MenuItem } from "./components/menu/types";
export { PartialOptions } from "overlayscrollbars";
export namespace Components {
    interface CfUiMenu {
        "height": string;
        "items": MenuItem[];
    }
    interface CfUiScrollbar {
        "height": string;
        "options": PartialOptions;
        "width": string;
    }
}
declare global {
    interface HTMLCfUiMenuElement extends Components.CfUiMenu, HTMLStencilElement {
    }
    var HTMLCfUiMenuElement: {
        prototype: HTMLCfUiMenuElement;
        new (): HTMLCfUiMenuElement;
    };
    interface HTMLCfUiScrollbarElement extends Components.CfUiScrollbar, HTMLStencilElement {
    }
    var HTMLCfUiScrollbarElement: {
        prototype: HTMLCfUiScrollbarElement;
        new (): HTMLCfUiScrollbarElement;
    };
    interface HTMLElementTagNameMap {
        "cf-ui-menu": HTMLCfUiMenuElement;
        "cf-ui-scrollbar": HTMLCfUiScrollbarElement;
    }
}
declare namespace LocalJSX {
    interface CfUiMenu {
        "height"?: string;
        "items"?: MenuItem[];
    }
    interface CfUiScrollbar {
        "height"?: string;
        "options"?: PartialOptions;
        "width"?: string;
    }
    interface IntrinsicElements {
        "cf-ui-menu": CfUiMenu;
        "cf-ui-scrollbar": CfUiScrollbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cf-ui-menu": LocalJSX.CfUiMenu & JSXBase.HTMLAttributes<HTMLCfUiMenuElement>;
            "cf-ui-scrollbar": LocalJSX.CfUiScrollbar & JSXBase.HTMLAttributes<HTMLCfUiScrollbarElement>;
        }
    }
}
