/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CfUiScrollbar {
        "height": string;
        "width": string;
    }
}
declare global {
    interface HTMLCfUiScrollbarElement extends Components.CfUiScrollbar, HTMLStencilElement {
    }
    var HTMLCfUiScrollbarElement: {
        prototype: HTMLCfUiScrollbarElement;
        new (): HTMLCfUiScrollbarElement;
    };
    interface HTMLElementTagNameMap {
        "cf-ui-scrollbar": HTMLCfUiScrollbarElement;
    }
}
declare namespace LocalJSX {
    interface CfUiScrollbar {
        "height"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "cf-ui-scrollbar": CfUiScrollbar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cf-ui-scrollbar": LocalJSX.CfUiScrollbar & JSXBase.HTMLAttributes<HTMLCfUiScrollbarElement>;
        }
    }
}
